language: node_js
sudo: required
services:
    - docker
before_install:
    - docker build -t yiftah/docker-react -f Dockerfile.dev . 
script:
    - docker run yiftah/docker-react npm run test -- --coverage

#deploy:
#    provider: elasticbeanstalk
#    region:
#   app: "docker"
#   env: "Docker-env"
#   bucket-name:
#   bucket-path:
#on:
#    branch: master
#   access_key_id: $AWS_ACCESS_KET
#secret_access_key:
